#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/goreadme

[ "$1" = "--check" ] || {
  exec bin/goreadme > README.md
}

[ "$(bin/goreadme)" = "$(cat README.md)" ] || {
  echo "README.md is out of date.  Try running script/readme"
  exit 1
}
