name: ci
on: [push]
jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: script/test
      - name: Lint
        run: script/lint
